version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"   # para aceptar jugadores no licenciados
      MEMORY: "2G"
      VERSION: "1.20.1"
      MOTD: "Servidor Franco - Docker"
    volumes:
      - ./minecraft-data:/data
    restart: unless-stopped
