name: Deploy Minecraft Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            mkdir -p /root/minecraft-server
            cd /root/minecraft-server
            echo "Updating server..."
            scp -o StrictHostKeyChecking=no $GITHUB_WORKSPACE/docker-compose.yml root@${{ secrets.DO_HOST }}:/root/minecraft-server/docker-compose.yml
            docker-compose pull
            docker-compose up -d
